COMPILER=gcc
COMPILER_ARGUMENTS=

SOURCE_FILES_CLIENT=src/client/*.c
SOURCE_FILES_SERVER=src/server/*.c

OUTPUT_FOLDER=target/
OUTPUT_FILE_CLIENT=clientapp
OUTPUT_FILE_SERVER=serverapp

build:
	rm -rf $(OUTPUT_FOLDER)
	mkdir $(OUTPUT_FOLDER)
	$(COMPILER) $(COMPILER_ARGUMENTS) $(SOURCE_FILES_CLIENT) -o $(OUTPUT_FOLDER)$(OUTPUT_FILE_CLIENT) 
	$(COMPILER) $(COMPILER_ARGUMENTS) $(SOURCE_FILES_SERVER) -o $(OUTPUT_FOLDER)$(OUTPUT_FILE_SERVER)

clean:
	rm -rf $(OUTPUT_FOLDER) 
